import { PT_Sans } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import AddBootstrap from "./AddBootstrap";
import Navbar from "@/components/Navbar";
const fontFamily = PT_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Ice Creams",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontFamily.className}>
        <AddBootstrap />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
